[tool.poetry]
name = "tableau_sdk"
version = "0.1.0"
description = ""
authors = ["yolo-kiyoshi"]

[tool.poetry.dependencies]
python = "^3.7"
tableauhyperapi = "^0.0.9746"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
